# Generated by Django 5.1 on 2024-08-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cpnn2_people_cpnum2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='mdate',
            field=models.CharField(max_length=25),
        ),
    ]
